// <auto-generated />
namespace SCRegistrationWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_RoomAssignment_DeleteFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_RoomAssignment_DeleteFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "201305080313265_Add_RoomAssignment_DeleteFlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
