// <auto-generated />
namespace SCRegistrationWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update_PaymentEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_PaymentEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201301280451559_Update_PaymentEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
