namespace SCRegistrationWeb.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using System.Collections.Generic;
    using SCRegistrationWeb.Models;

    internal sealed class Configuration : DbMigrationsConfiguration<SCRegistrationWeb.Models.SCRegistrationContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(SCRegistrationWeb.Models.SCRegistrationContext context)
        {
            //context.Statuses.AddOrUpdate(
            //     s => s.StatusID,
            //     new Status { StatusID = 1, Name = "Incomplete 不完整" },
            //     new Status { StatusID = 2, Name = "Pending 待完成" },
            //     new Status { StatusID = 3, Name = "Confirmed 证实了" },
            //     new Status { StatusID = 4, Name = "Cancelled 取消了" },
            //     new Status { StatusID = 5, Name = "Checked In" },
            //     new Status { StatusID = 6, Name = "Checked Out" }
            //     );

            //context.Services.AddOrUpdate(
            //    v => v.ServiceID,
            //    new Service { ServiceID = 1, Name = "English" },
            //    new Service { ServiceID = 2, Name = "Mandarin 普通话" },
            //    new Service { ServiceID = 3, Name = "Cantonese 广东话" },
            //    new Service { ServiceID = 4, Name = "T4C West 西区分堂" },
            //    new Service { ServiceID = 5, Name = "Youth Group" },
            //    new Service { ServiceID = 6, Name = "Children" },
            //    new Service { ServiceID = 7, Name = "Nursery" }
            //    );

            //context.AgeRanges.AddOrUpdate(
            //    a => a.AgeRangeID,
            //    new AgeRange { AgeRangeID = 1, Name = "0-1 yrs" },
            //    new AgeRange { AgeRangeID = 2, Name = "1-5 yrs" },
            //    new AgeRange { AgeRangeID = 3, Name = "6-12 yrs" },
            //    new AgeRange { AgeRangeID = 4, Name = "Teenager" },
            //    new AgeRange { AgeRangeID = 5, Name = "Adult" },
            //    new AgeRange { AgeRangeID = 6, Name = "Senior" }
            //    );

            //context.Genders.AddOrUpdate(
            //     a => a.GenderID,
            //     new Gender { GenderID = 1, Name = "Male 男" },
            //     new Gender { GenderID = 2, Name = "Female 女" }
            //     );

            //context.Fellowships.AddOrUpdate(
            //    a => a.FellowshipID,
            //    new Fellowship { FellowshipID = 1, ServiceID = 1, Name = "No Fellowship Selected" },
            //    new Fellowship { FellowshipID = 2, ServiceID = 2, Name = "None Selected 没有选择" },
            //    new Fellowship { FellowshipID = 3, ServiceID = 3, Name = "None Selected 没有选择" },
            //    new Fellowship { FellowshipID = 4, ServiceID = 4, Name = "None Selected 没有选择" },
            //    new Fellowship { FellowshipID = 5, ServiceID = 5, Name = "No Fellowships" },
            //    new Fellowship { FellowshipID = 6, ServiceID = 6, Name = "No Fellowships" },
            //    new Fellowship { FellowshipID = 7, ServiceID = 7, Name = "No Fellowships" },
            //    new Fellowship { FellowshipID = 8, ServiceID = 1, Name = "Couples Group South" },
            //    new Fellowship { FellowshipID = 9, ServiceID = 1, Name = "College Group" },
            //    new Fellowship { FellowshipID = 10, ServiceID = 1, Name = "English District" },
            //    new Fellowship { FellowshipID = 11, ServiceID = 1, Name = "Plymouth Fellowship" },
            //    new Fellowship { FellowshipID = 12, ServiceID = 1, Name = "Young Profs/Grad Student" },
            //    new Fellowship { FellowshipID = 13, ServiceID = 1, Name = "Others" },
            //    new Fellowship { FellowshipID = 14, ServiceID = 2, Name = "Joy 喜樂" },
            //    new Fellowship { FellowshipID = 15, ServiceID = 2, Name = "Living Water 活水" },
            //    new Fellowship { FellowshipID = 16, ServiceID = 2, Name = "New Life 新生命" },
            //    new Fellowship { FellowshipID = 17, ServiceID = 2, Name = "West 西區" },
            //    new Fellowship { FellowshipID = 18, ServiceID = 2, Name = "Agape 仁愛" },
            //    new Fellowship { FellowshipID = 19, ServiceID = 2, Name = "Others 另外" },
            //    new Fellowship { FellowshipID = 20, ServiceID = 3, Name = "Cantonese Career 粵語就業" },
            //    new Fellowship { FellowshipID = 21, ServiceID = 3, Name = "Cantonese Student 粵語學生" },
            //    new Fellowship { FellowshipID = 22, ServiceID = 3, Name = "Chong Yuen 狀元" },
            //    new Fellowship { FellowshipID = 23, ServiceID = 3, Name = "Fung Sing 豐盛" },
            //    new Fellowship { FellowshipID = 24, ServiceID = 3, Name = "Grace 加恩" },
            //    new Fellowship { FellowshipID = 24, ServiceID = 3, Name = "Life 生命" },
            //    new Fellowship { FellowshipID = 24, ServiceID = 3, Name = "Song of Songs 雅歌" },
            //    new Fellowship { FellowshipID = 25, ServiceID = 3, Name = "Others 另外" },
            //    new Fellowship { FellowshipID = 26, ServiceID = 4, Name = "Albert He"},
            //    new Fellowship { FellowshipID = 27, ServiceID = 4, Name = "Longfei Hu" },
            //    new Fellowship { FellowshipID = 28, ServiceID = 4, Name = "Jie Gong" },
            //    new Fellowship { FellowshipID = 29, ServiceID = 4, Name = "Richard He" },
            //    new Fellowship { FellowshipID = 30, ServiceID = 4, Name = "Bingwen Hao" },
            //    new Fellowship { FellowshipID = 31, ServiceID = 4, Name = "Sherman Chan" }
            //    );

            //context.RegTypes.AddOrUpdate(
            //     a => a.RegTypeID,
            //     new RegType { RegTypeID = 1, Name = "Full Time 全時間" },
            //     new RegType { RegTypeID = 2, Name = "Part Time 部分時間" }
            //     );

            //context.RegPrices.AddOrUpdate(
            //    a => a.AgeRangeID,
            //    new RegPrice { AgeRangeID = 1, PartTimePrice = (decimal)10, FullTimePrice = (decimal)10},
            //    new RegPrice { AgeRangeID = 2, PartTimePrice = (decimal)25, FullTimePrice = (decimal)45},
            //    new RegPrice { AgeRangeID = 3, PartTimePrice = (decimal)40, FullTimePrice = (decimal)70},
            //    new RegPrice { AgeRangeID = 4, PartTimePrice = (decimal)55, FullTimePrice = (decimal)95},
            //    new RegPrice { AgeRangeID = 5, PartTimePrice = (decimal)55, FullTimePrice = (decimal)95},
            //    new RegPrice { AgeRangeID = 6, PartTimePrice = (decimal)55, FullTimePrice = (decimal)95}
            //    );

            //context.RoomTypes.AddOrUpdate(
            //    a => a.RoomTypeID,
            //    new RoomType { RoomTypeID = 1, RegTypeID = 1, Name = "No Preference 没有偏好" },
            //    new RoomType { RoomTypeID = 2, RegTypeID = 2, Name = "No Room 无房必要" },
            //    new RoomType { RoomTypeID = 3, RegTypeID = 1, Name = "Family Room" },
            //    new RoomType { RoomTypeID = 4, RegTypeID = 1, Name = "Couple Room " },
            //    new RoomType { RoomTypeID = 5, RegTypeID = 1, Name = "Single-sex Dorm" },
            //    new RoomType { RoomTypeID = 6, RegTypeID = 1, Name = "Handicapped 残废" }
            //    );


            //context.PmtStatuses.AddOrUpdate(
            //    a => a.PmtStatusID,
            //    new PmtStatus { PmtStatusID = 1, Name = "Pending" },
            //    new PmtStatus { PmtStatusID = 2, Name = "Approved" },
            //    new PmtStatus { PmtStatusID = 3, Name = "Declined" }
            //    );

            //context.PmtTypes.AddOrUpdate(
            //    a => a.PmtTypeID,
            //    new PmtType { PmtTypeID = 1, Name = "Scholorship" },
            //    new PmtType { PmtTypeID = 2, Name = "Cash" },
            //    new PmtType { PmtTypeID = 3, Name = "Check" },
            //    new PmtType { PmtTypeID = 4, Name = "Refund" },
            //    new PmtType { PmtTypeID = 5, Name = "Adjustmet" },
            //    new PmtType { PmtTypeID = 6, Name = "Credit Card"}

            //    );

            context.Buildings.AddOrUpdate(
                a => a.BuildingID,
                new Building { BuildingID = 1, Name = "Conley Hall", RoomTypeID = 3},
                new Building { BuildingID = 2, Name = "Hardwick Hall", RoomTypeID = 3 },
                new Building { BuildingID = 3, Name = "Main East 2nd Flr", RoomTypeID = 5 },
                new Building { BuildingID = 4, Name = "Main East 3rd Flr", RoomTypeID = 5 },
                new Building { BuildingID = 5, Name = "Main East 4th Flr", RoomTypeID = 5 },
                new Building { BuildingID = 6, Name = "Miller Hall", RoomTypeID = 4 },
                new Building { BuildingID = 7, Name = "Richardson 1st Flr", RoomTypeID = 4 },
                new Building { BuildingID = 8, Name = "Richardson 2nd Flr", RoomTypeID = 4 },
                new Building { BuildingID = 9, Name = "Richardson 3rd Flr", RoomTypeID = 4 },
                new Building { BuildingID = 10, Name = "Strohm Hall 1st Flr", RoomTypeID = 4 },
                new Building { BuildingID = 11, Name = "Strohm Hall 2nd Flr", RoomTypeID = 4 },
                new Building { BuildingID = 12, Name = "Strohm Hall 3rd Flr", RoomTypeID = 4 },
                new Building { BuildingID = 13, Name = "Tewinkel 1st Flr", RoomTypeID = 6 },
                new Building { BuildingID = 14, Name = "Tewinkel 2nd Flr", RoomTypeID = 3 },
                new Building { BuildingID = 15, Name = "Weldin 1st Flr", RoomTypeID = 6 },
                new Building { BuildingID = 16, Name = "Weldin 2nd Flr", RoomTypeID = 3 }
                );

            context.Rooms.AddOrUpdate(
                a => a.RoomID,
                new Room { RoomID = 1, Name = "102", BuildingID = 1, NumOfBeds = 2},
                new Room { RoomID = 2, Name = "103", BuildingID = 1, NumOfBeds = 4},
                new Room { RoomID = 3, Name = "105", BuildingID = 1, NumOfBeds = 4},
                new Room { RoomID = 4, Name = "106", BuildingID = 1, NumOfBeds = 2},
                new Room { RoomID = 5, Name = "107", BuildingID = 1, NumOfBeds = 4},
                new Room { RoomID = 6, Name = "109", BuildingID = 1, NumOfBeds = 4},
                new Room { RoomID = 7, Name = "110", BuildingID = 1, NumOfBeds = 2},
                new Room { RoomID = 8, Name = "111", BuildingID = 1, NumOfBeds = 4},
                new Room { RoomID = 9, Name = "1A", BuildingID = 2, NumOfBeds = 2},
                new Room { RoomID = 10, Name = "1B", BuildingID = 2, NumOfBeds = 3},
                new Room { RoomID = 11, Name = "1C", BuildingID = 2, NumOfBeds = 2},
                new Room { RoomID = 12, Name = "2A", BuildingID = 2, NumOfBeds = 2},
                new Room { RoomID = 13, Name = "2B", BuildingID = 2, NumOfBeds = 3},
                new Room { RoomID = 14, Name = "2C", BuildingID = 2, NumOfBeds = 2},
                new Room { RoomID = 15, Name = "3A", BuildingID = 2, NumOfBeds = 2},
                new Room { RoomID = 16, Name = "3B", BuildingID = 2, NumOfBeds = 3},
                new Room { RoomID = 17, Name = "3C", BuildingID = 2, NumOfBeds = 2},
                new Room { RoomID = 18, Name = "4A", BuildingID = 2, NumOfBeds = 2},
                new Room { RoomID = 19, Name = "4B", BuildingID = 2, NumOfBeds = 3},
                new Room { RoomID = 20, Name = "4C", BuildingID = 2, NumOfBeds = 2},
                new Room { RoomID = 21, Name = "268A", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 22, Name = "268B", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 23, Name = "269A", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 24, Name = "269B", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 25, Name = "270", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 26, Name = "271", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 27, Name = "273", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 28, Name = "275A", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 29, Name = "275B", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 30, Name = "275C", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 31, Name = "275D", BuildingID = 3, NumOfBeds = 2},
                new Room { RoomID = 32, Name = "369", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 33, Name = "370", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 34, Name = "371", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 35, Name = "372", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 36, Name = "373", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 37, Name = "374", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 38, Name = "376", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 39, Name = "382", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 40, Name = "386", BuildingID = 4, NumOfBeds = 1},
                new Room { RoomID = 41, Name = "387", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 42, Name = "388", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 43, Name = "389", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 44, Name = "390", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 45, Name = "391", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 46, Name = "393", BuildingID = 4, NumOfBeds = 2},
                new Room { RoomID = 47, Name = "441", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 48, Name = "442", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 49, Name = "443", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 50, Name = "444", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 51, Name = "445", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 52, Name = "446", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 53, Name = "450", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 54, Name = "452", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 55, Name = "454", BuildingID = 5, NumOfBeds = 1},
                new Room { RoomID = 56, Name = "456", BuildingID = 5, NumOfBeds = 1},
                new Room { RoomID = 57, Name = "457", BuildingID = 5, NumOfBeds = 1},
                new Room { RoomID = 58, Name = "458", BuildingID = 5, NumOfBeds = 1},
                new Room { RoomID = 59, Name = "459", BuildingID = 5, NumOfBeds = 1},
                new Room { RoomID = 60, Name = "460", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 61, Name = "461", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 62, Name = "462", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 63, Name = "463", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 64, Name = "466", BuildingID = 5, NumOfBeds = 2},
                new Room { RoomID = 65, Name = "1A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 66, Name = "1B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 67, Name = "1C", BuildingID = 6, NumOfBeds = 2},                
                new Room { RoomID = 68, Name = "2A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 69, Name = "2B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 70, Name = "2C", BuildingID = 6, NumOfBeds = 2},    
                new Room { RoomID = 71, Name = "3A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 72, Name = "3B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 73, Name = "3C", BuildingID = 6, NumOfBeds = 2},    
                new Room { RoomID = 74, Name = "4A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 75, Name = "4B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 76, Name = "4C", BuildingID = 6, NumOfBeds = 2},    
                new Room { RoomID = 77, Name = "5A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 78, Name = "5B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 79, Name = "5C", BuildingID = 6, NumOfBeds = 2},    
                new Room { RoomID = 80, Name = "6A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 81, Name = "6B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 82, Name = "6C", BuildingID = 6, NumOfBeds = 2},    
                new Room { RoomID = 83, Name = "7A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 84, Name = "7B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 85, Name = "7C", BuildingID = 6, NumOfBeds = 2},    
                new Room { RoomID = 86, Name = "8A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 87, Name = "8B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 88, Name = "9A", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 89, Name = "9B", BuildingID = 6, NumOfBeds = 2},
                new Room { RoomID = 90, Name = "9C", BuildingID = 6, NumOfBeds = 2},    
                new Room { RoomID = 91, Name = "104A", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 92, Name = "104B", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 93, Name = "108A", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 94, Name = "108B", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 95, Name = "112A", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 96, Name = "112B", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 97, Name = "116A", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 98, Name = "116B", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 99, Name = "120A", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 100, Name = "120B", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 101, Name = "124A", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 102, Name = "124B", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 103, Name = "128A", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 104, Name = "128B", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 105, Name = "132A", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 106, Name = "132B", BuildingID = 7, NumOfBeds = 2},    
                new Room { RoomID = 107, Name = "204A", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 108, Name = "204B", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 109, Name = "208A", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 110, Name = "208B", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 111, Name = "212A", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 112, Name = "212B", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 113, Name = "216A", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 114, Name = "216B", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 115, Name = "220A", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 116, Name = "220B", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 117, Name = "224A", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 118, Name = "224B", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 119, Name = "232A", BuildingID = 8, NumOfBeds = 2},    
                new Room { RoomID = 120, Name = "304A", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 121, Name = "304B", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 122, Name = "308A", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 123, Name = "308B", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 124, Name = "312A", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 125, Name = "312B", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 126, Name = "316A", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 127, Name = "316B", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 128, Name = "320A", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 129, Name = "320B", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 130, Name = "324A", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 131, Name = "324B", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 132, Name = "328A", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 133, Name = "328B", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 134, Name = "332A", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 135, Name = "332B", BuildingID = 9, NumOfBeds = 2},    
                new Room { RoomID = 136, Name = "104A", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 137, Name = "104B", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 138, Name = "108A", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 139, Name = "108B", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 140, Name = "112A", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 141, Name = "112B", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 142, Name = "116A", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 143, Name = "116B", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 144, Name = "120A", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 145, Name = "120B", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 146, Name = "124A", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 147, Name = "124B", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 148, Name = "128A", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 149, Name = "128B", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 150, Name = "132A", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 151, Name = "132B", BuildingID = 10, NumOfBeds = 2},    
                new Room { RoomID = 152, Name = "204A", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 153, Name = "204B", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 154, Name = "208A", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 155, Name = "208B", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 156, Name = "212A", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 157, Name = "212B", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 158, Name = "216A", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 159, Name = "216B", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 160, Name = "220A", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 161, Name = "220B", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 162, Name = "224A", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 163, Name = "224B", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 164, Name = "228A", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 165, Name = "228B", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 166, Name = "232A", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 167, Name = "232B", BuildingID = 11, NumOfBeds = 2},    
                new Room { RoomID = 168, Name = "304A", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 169, Name = "304B", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 170, Name = "308A", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 171, Name = "308B", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 172, Name = "312A", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 173, Name = "312B", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 174, Name = "316A", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 175, Name = "316B", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 176, Name = "320A", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 177, Name = "320B", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 178, Name = "324A", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 179, Name = "324B", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 180, Name = "332A", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 181, Name = "332B", BuildingID = 12, NumOfBeds = 2},    
                new Room { RoomID = 182, Name = "110A", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 183, Name = "110B", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 184, Name = "110C", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 185, Name = "120A", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 186, Name = "120B", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 187, Name = "120C", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 188, Name = "140A", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 189, Name = "140B", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 190, Name = "140C", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 191, Name = "150A", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 192, Name = "150B", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 193, Name = "150C", BuildingID = 13, NumOfBeds = 2},    
                new Room { RoomID = 194, Name = "210A", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 195, Name = "210B", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 196, Name = "210C", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 197, Name = "220A", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 198, Name = "220B", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 199, Name = "220C", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 200, Name = "230A", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 201, Name = "230B", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 202, Name = "240A", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 203, Name = "240B", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 204, Name = "240C", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 205, Name = "250A", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 206, Name = "250B", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 207, Name = "250C", BuildingID = 14, NumOfBeds = 2},    
                new Room { RoomID = 208, Name = "110A", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 209, Name = "110B", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 210, Name = "110C", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 211, Name = "120A", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 212, Name = "120B", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 213, Name = "120C", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 214, Name = "140A", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 215, Name = "140B", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 216, Name = "140C", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 217, Name = "150A", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 218, Name = "150B", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 219, Name = "150C", BuildingID = 15, NumOfBeds = 2},    
                new Room { RoomID = 220, Name = "210A", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 221, Name = "210B", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 222, Name = "210C", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 223, Name = "220A", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 224, Name = "220B", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 225, Name = "220C", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 226, Name = "230A", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 227, Name = "230B", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 228, Name = "240A", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 229, Name = "240B", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 230, Name = "240C", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 231, Name = "250A", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 232, Name = "250B", BuildingID = 16, NumOfBeds = 2},    
                new Room { RoomID = 233, Name = "250C", BuildingID = 16, NumOfBeds = 2}
                );

        }
    }
}
